sudo: required
language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    packages:
    - libssl-dev
    - dc
cache: cargo
script:
- cargo clean
- cargo build
- cargo test
- [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] && cargo bench
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)

    curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
    chmod a+x /tmp/travis-automerge
    BRANCHES_TO_MERGE_REGEX='^f/' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=rik0/rdc /tmp/travis-automerge
  fi

env:
  global:
    secure: BQ9OpOWFJBt5uv1q9kzn57exofvS0xeRbUdkIGQGL1gnRFAfuRx88sC/CIqrB93qlVNy24TlFykqpQY8Q2e8KoiGep4xK1Yvd4sxWC1RO6TK8IWJDEu+yyxcnYQMxmQxNwoeRX7PJrOBJ+cJNaKLGt4xY8B5Khd+sQfA/oIBFUxi0EdGe8DWszeCiCx95BYy1TNT0LqM8YcafHf2SjyfhhfJNaGwd5eRCT/V2CMUOj5mNQ898kCPXELcQmqPYzdLT1Ab2m0T6jaY4RCUXr1/rFhUZEgzWBgD+4kqZBH8Jr0ppAB7qazMXRf+XxjT25CGDRNWAt3HVDT9dHoxdGLdnjCwmk+TAF/zvIooF7ZJVjKo0PRH1ITDm0z6SKvhUKveY15SMN6qXrW1SoHzPwUfgQj9QFcrCq1NptQkOigVxdn4LVJcNs4yjYzxALgF5hD0C19BfDtZxTi92wY7fyElrg+IbiT2APOJQtQqKZZLksfxU95LQMuWOexQV+HhtNam8rJpubAAsZtLRTB2qglcyj2IjwC7XxZSX6x5oQvga2p4KaVstIkEOGtwMghfVwWK+WHevNT9QtDt0IZdvzA9fp7f5afojCM8RlYapMt9Ej1ZHgellhPJBLm0SF/tYDs3kWBXk6i3PZymA2JtQehWeBA99eN+OQ+aMByavgq7qXY=
